app = "n8n-fly-deploy-3q7rrq"

[build]
  image = "n8nio/n8n"

[env]
  DB_TYPE = "postgresdb"
  DB_POSTGRESDB_HOST = "db.ugabnyhbsvtefdfzimcm.supabase.co"
  DB_POSTGRESDB_PORT = "5432"
  DB_POSTGRESDB_DATABASE = "postgres"
  DB_POSTGRESDB_USER = "postgres"

  N8N_PORT = "5678"
  N8N_HOST = "0.0.0.0"
  WEBHOOK_TUNNEL_URL = "https://n8n-fly-deploy-3q7rrq.fly.dev"

  # OPTIONAL: disable telemetry
  N8N_DIAGNOSTICS_ENABLED = "false"
  N8N_DISABLE_PRODUCTION_MAIN_LOG = "true"

[[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
